networks:
  laravel:
    driver: bridge

services:
  php:
    build:
        context: .
        dockerfile: Dockerfile  
    container_name: php
    volumes:
      - ./laravel/:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    expose:
      - "9000"
    entrypoint: ["sh", "/usr/local/bin/init.sh", "php-fpm"]

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile  
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel/:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/default.conf
      - ./nginx-logs:/var/log/nginx
    networks:
      - laravel
    depends_on:
      - php